version: 1.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
build_script:
- ps: dotnet build -c Release
- ps: dotnet test Tardis.UnitTests
- ps: dotnet pack